### PR TITLE
Sensor offsets

### PR DESCRIPTION
**Pull request by luxiya01**
1. Requires user to supply a roll compensation to the MBES data when aligning `all_mbes_pings` with `all_nav_entries`.
2. Add `sensor_offset` package that defines `SonarOffset` struct and functions to parse offset files in a specific format.
2. Add a `set_sonar_offsest` method to Drapers (`BaseDraper`, `ViewDraper` and `MapDraper`) and the python bindings `MeasDataDraper` and `MapImageDraper`.

### CODE REVIEW

**Comment by nilsbore** [comment]
Looking good! As we discussed, I'd like the sonar offset to be a setter rather than in the constructor. Even if there is a default argument in C++, I don't think that can be reflected in the python bindings. And I don't want to break students' code.

**Comment by nilsbore** [comment]
Ok, I went through some of this now. Another concern is this change: https://github.com/nilsbore/auvlib/pull/81/files#diff-42eacd00c8fc1349fde3dea29ee04051acab114f71cba7e26663ddc7396cd57dR235 which would also break some code (I assume). My suggestion would be change the name of this function to something like `convert_matched_entries_with_roll` and add another one with the old signature (`convert_matched_entries`) that just passes on the argument to `convert_matched_entries_with_roll`, together with `roll=0`.

**Comment by nilsbore** [comment]
Of course, if we find out that we always needs to supply some kind of roll compensation and figure out what exactly that roll should be, we should revisit these functions.

**Comment by luxiya01** [comment]
> Ok, I went through some of this now. Another concern is this change: https://github.com/nilsbore/auvlib/pull/81/files#diff-42eacd00c8fc1349fde3dea29ee04051acab114f71cba7e26663ddc7396cd57dR235 which would also break some code (I assume). My suggestion would be change the name of this function to something like `convert_matched_entries_with_roll` and add another one with the old signature (`convert_matched_entries`) that just passes on the argument to `convert_matched_entries_with_roll`, together with `roll=0`.

Actually I don't think this is going to break the student's code, since a default argument has been added to the python binding, the `convert_matched_entries` can be called like previously without roll, or with a row argument.

**Comment by nilsbore** [comment]
Looks good! Resolve the conflicts and I will merge this.

**Comment by luxiya01** [comment]
Resolved!

**Pull request merged**
