### PR TITLE
Added opencv dep for linking benchmark lib on external project

### PR DESCRIPTION
**Pull request by ignaciotb**

### CODE REVIEW

**Comment by nilsbore** [comment]
@ignaciotb It seems like the opencv version that ships with Ubuntu does not have `imgcodecs` (see travis output). Are you using the ros version of opencv? Any ideas for workarounds?

**Comment by ignaciotb** [comment]
It looks like you can install it from the APT repo as libopencv-imgcodecs-dev. Can you add it as a dep on the README?

**Comment by ignaciotb** [comment]
> @ignaciotb It seems like the opencv version that ships with Ubuntu does not have `imgcodecs` (see travis output). Are you using the ros version of opencv? Any ideas for workarounds?

It looks like you can install it from the APT repo as libopencv-imgcodecs-dev. Can you add it as a dep on the README?

**Comment by ignaciotb** [comment]
Also, I've added a new commit removing the depth limit on the reading of MBES pings

**Comment by nilsbore** [comment]
I tried this on CI with ubuntu 16.04 (see above commit on your branch :)) and it complains: `E: Unable to locate package libopencv-imgcodecs-dev` when trying to install with apt. It think it might be in ROS, and that is too big of a dependency here. Closing until you can find a reasonable solution for this.

**Pull request closed without merging**
