### PR TITLE
Update jsf_data library

### PR DESCRIPTION
**Pull request by xyp8023**
Hi, I added a few things in the jsf_data library, the main idea is to add python interface for jsf_dvl_ping, and match the sound velocity in jsf_dvl_ping to jsf_sss_ping, so that slant range can be calculated. Also a few attributes to jsf_sss_ping are added.

### CODE REVIEW

**Comment by nilsbore** [comment]
I don't know why travis is not showing, but that seems to have worked: https://travis-ci.org/github/nilsbore/auvlib/builds/669798473

**Comment by nilsbore** [comment]
Appveyor failed, I'm trying to find out why

**Comment by xyp8023** [comment]
I found someone says:   "Adding the line ADD_COMPILE_FLAG("/D_ENABLE_EXTENDED_ALIGNED_STORAGE") to CMakeLists.txt" could fix it.

**Comment by xyp8023** [comment]
Oh, that is actually for CMakeLists.txt of VS2017. 
https://github.com/WebAssembly/binaryen/pull/1823/commits/e8ac331501c91373a77967a5f609b0912aa05fc4?w=1#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by nilsbore** [comment]
But I don't see the actual error in the appveyour output, do you? I see that you added some define for aligned storage, what is it used for?

**Comment by nilsbore** [comment]
On another note, I have to review https://github.com/nilsbore/auvlib/pull/58 before I can merge this (since this is working from that branch). I don't really grasp all of John's changes yet, so that will take a bit more time. In the future, try to keep new stuff on as clean a branch as possible.

**Comment by xyp8023** [comment]
The error in the appveuour output is:
[00:16:42] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]

**Comment by xyp8023** [comment]
> On another note, I have to review #58 before I can merge this (since this is working from that branch). I don't really grasp all of John's changes yet, so that will take a bit more time. In the future, try to keep new stuff on as clean a branch as possible.

Right, I forgot to remove John's changes in the this branch. But I did try to use his code to parse the xtf files, it seemed to work.

**Comment by xyp8023** [comment]
> But I don't see the actual error in the appveyour output, do you? I see that you added some define for aligned storage, what is it used for?

The line I added was no good, I misunderstood how other people have fixed it.

**Comment by nilsbore** [comment]
Do you know which change of yours triggered this error with the aligned storage?

**Comment by xyp8023** [comment]
> Do you know which change of yours triggered this error with the aligned storage?

I am not sure, but I would guess it is in the "match_sound_vel" when I try to assign the sound_vel to jsf_sss_ping

**Comment by nilsbore** [comment]
I think it might simply be that you are trying to serialize `std::unordered_map` with cereal, but there is no include of the cereal serialization function for that container, like here: https://github.com/nilsbore/auvlib/blob/5b54b9fc0e7e609e04e3ebe591f122548e265496/src/data_tools/include/data_tools/std_data.h#L18 . I would suggest trying to add that line (`#include <cereal/types/unordered_map.hpp>`) in `std_data.h`.

**Comment by xyp8023** [comment]
> #include <cereal/types/unordered_map.hpp>

I will try that.

**Comment by xyp8023** [comment]
> I think it might simply be that you are trying to serialize `std::unordered_map` with cereal, but there is no include of the cereal serialization function for that container, like here:
> 
> https://github.com/nilsbore/auvlib/blob/5b54b9fc0e7e609e04e3ebe591f122548e265496/src/data_tools/include/data_tools/std_data.h#L18
> 
> . I would suggest trying to add that line (`#include <cereal/types/unordered_map.hpp>`) in `std_data.h`. And remove the define you added.

But before this PR, there is std::unordered_map in jsf_dvl_ping already.

**Comment by nilsbore** [comment]
Hmm, ok, there might be something else going on then...

**Comment by nilsbore** [comment]
Yes, the culprit seems to be something else. Let's continue tomorrow.

**Comment by xyp8023** [comment]
> Yes, the culprit seems to be something else. Let's continue tomorrow.

okay

**Comment by xyp8023** [comment]
The error seems to be in jsf_data.cpp between line 86 and line 448, because there is a warning at line 86 and another warning at line 448, but an error in between. 

[00:07:04]   jsf_data.cpp
[00:07:04]   Unknown compiler version - please run the configure tests and report the results
[00:07:04] cl : Command line warning D9002: ignoring unknown option '-O3' [C:\projects\auvlib\build\src\pybathy_maps\pydraw_map.vcxproj]
[00:07:04] cl : Command line warning D9002: ignoring unknown option '-fPIC' [C:\projects\auvlib\build\src\pybathy_maps\pydraw_map.vcxproj]
[00:07:04] C:\projects\auvlib\src\eigen_cereal\include\eigen_cereal/eigen_cereal.h(17): warning C4244: 'initializing': conversion from '__int64' to 'int32_t', possible loss of data [C:\projects\auvlib\build\src\pydata_tools\pyall_data.vcxproj]
[00:07:04] C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(50): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05]   pydraw_map.cpp
[00:07:05] C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(51): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05] C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(56): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05]   C:\projects\auvlib\src\cereal\include\cereal/cereal.hpp(505): note: see reference to function template instantiation 'void cereal::save<AA,double,3,1,0,3,1>(Archive &,const Eigen::Matrix<double,3,1,0,3,1> &)' being compiled
[00:07:05]           with
[00:07:05]           [
[00:07:05]               AA=cereal::BinaryOutputArchive,
[00:07:05]               Archive=cereal::BinaryOutputArchive
[00:07:05]           ]
[00:07:05]   C:\projects\auvlib\src\cereal\include\cereal/cereal.hpp(417): note: see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,1>::processImpl<Eigen::Matrix<double,3,1,0,3,1>,0>(const T &)' being compiled
[00:07:05]           with
[00:07:05]           [
[00:07:05]               ArchiveType=cereal::BinaryOutputArchive,
[00:07:05]               T=Eigen::Matrix<double,3,1,0,3,1>
[00:07:05] C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(63): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05]           ]
[00:07:05] C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(86): warning C4018: '<': signed/unsigned mismatch [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05]   C:\projects\auvlib\src\cereal\include\cereal/cereal.hpp(417): note: see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,1>::processImpl<Eigen::Matrix<double,3,1,0,3,1>,0>(const T &)' being compiled
[00:07:05]           with
[00:07:05]           [
[00:07:05]               ArchiveType=cereal::BinaryOutputArchive,
[00:07:05]               T=Eigen::Matrix<double,3,1,0,3,1>
[00:07:05]           ]
[00:07:05]   C:\projects\auvlib\src\cereal\include\cereal/cereal.hpp(311): note: see reference to function template instantiation 'void cereal::OutputArchive<cereal::BinaryOutputArchive,1>::process<const Eigen::Matrix<double,3,1,0,3,1>&>(T)' being compiled
[00:07:05]           with
[00:07:05]           [
[00:07:05]               T=const Eigen::Matrix<double,3,1,0,3,1> &
[00:07:05] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [C:\projects\auvlib\build\src\data_tools\jsf_data.vcxproj]
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1291): note: see reference to class template instantiation 'std::_Aligned<272,16,double,false>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1298): note: see reference to class template instantiation 'std::_Aligned<272,16,int,false>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1305): note: see reference to class template instantiation 'std::_Aligned<272,16,short,false>' being compiled
[00:07:05]           ]
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1312): note: see reference to class template instantiation 'std::_Aligned<272,16,char,false>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1320): note: see reference to class template instantiation 'std::aligned_storage<272,16>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1352): note: see reference to alias template instantiation 'std::aligned_storage_t<272,16>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(1357): note: see reference to class template instantiation 'std::aligned_union<0,_Ty>' being compiled
[00:07:05]           with
[00:07:05]           [
[00:07:05]               _Ty=jsf_data::jsf_dvl_ping
[00:07:05]           ]
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\algorithm(79): note: see reference to alias template instantiation 'std::aligned_union_t<0,jsf_data::jsf_dvl_ping>' being compiled
[00:07:05]   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\algorithm(4274): note: see reference to class template instantiation 'std::_Optimistic_temporary_buffer<jsf_data::jsf_dvl_ping>' being compiled
[00:07:05]   C:\projects\auvlib\src\data_tools\src\jsf_data.cpp(448): note: see reference to function template instantiation 'void std::stable_sort<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,jsf_data::match_sound_vel::<lambda_282701942c233423c13c9ddf612ca1a3>>(_BidIt,_BidIt,_Pr)' being compiled
[00:07:05]           with

**Comment by nilsbore** [comment]
Closing in favour of https://github.com/nilsbore/auvlib/pull/62

**Pull request closed without merging**
