### PR TITLE
Modified the xtf reader to read Hugin files

### PR DESCRIPTION
**Pull request by johnfolk**
Hi Nils
Mostly this is two new methods for creating waterfall images from the xtf files.  
But in xtfreader.c I totally deleted your code and wrote a much simplier parser that did not have the limit on the size of the records.  I tested this on the hugin data only.  So it may be some unknown issues.

### CODE REVIEW

**Comment by johnfolk** [comment]
I think I have done this right now so the pull request for those extra functions should be there.

**Comment by nilsbore** [comment]
@johnfolk Yeah, looks good. I will need to modify a little bit to fit with python libraries and so on, but should be quite easy. I will push to your branch so we can merge this PR eventually.

**Comment by johnfolk** [comment]
Fixed the xtf processing to run faster and more robustly find the nadir and artifact.

**Comment by nilsbore** [comment]
This is too old now, and it adds a lot of stuff without any python interfaces. I'll see if I can merge some of the stuff through @xyp8023 's changes.

**Pull request closed without merging**
