### PR TITLE
Altitude reading 

### PR DESCRIPTION
**Pull request by xyp8023**
Sensor primary altitude reading from .xtf files is added, in theory it should be the first bottom return.  

One way to check is draping with a much higher column number than 256, say 2048, and calculate the slant range of the first hits in every ping (compare to the altitude reading). If they are off by a lot, then something must be wrong, one thing I could think of is that maybe the set sidescan sensor offset is a very bad estimation.

### CODE REVIEW

**Comment by nilsbore** [comment]
This is a great addition. However, it means that all old `.cereal` files with xtf pings will not be readable anymore. I think I will merge this with a new `1.0` branch in the meanwhile where I will merge breaking changes. `1.0` will then be merged to `master` when we're ready. Does that sound OK?

**Comment by xyp8023** [comment]
Yes, that’s probably a good idea, and I’m thinking there’s more could be added to ‘1.0’. One thing I could think of is calculate the ground range based on altitude and slant range, and a function making waterfall image with ground range, i.e. waterfall image after slant range correction.

**Comment by nilsbore** [comment]
Yeah, basically everything that we want to do that is a breaking change should go into `1.0`. Add all your suggestions to this issue: https://github.com/nilsbore/auvlib/issues/49

**Comment by nilsbore** [comment]
Closing in favour of https://github.com/nilsbore/auvlib/pull/65

**Pull request closed without merging**
